pipeline{

	agent any

	environment {
		DOCKERHUB_CREDENTIALS=credentials('docker')
	}

	stages {
	    
	    stage('gitclone') {

			steps {
				git 'https://github.com/jenyaTopol/MyDevOpsPyProj'
			}
		}

		stage('Build') {

			steps {
				sh 'docker build -t enyatopol/mypythonapp:latest .'
			}
		}

		stage('Login') {

			steps {
				sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
			}
		}

		stage('Push') {

			steps {
				sh 'docker push enyatopol/mypythonapp:latest'
			}
		}
	}

	post {
		always {
			sh 'docker logout'
		}
		
	}

}
